cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fuse-ld=mold" -DLLVM_INCLUDE_TOOLS=ON -DLLVM_BUILD_RUNTIME=Off -DLLVM_INCLUDE_TESTS=Off -DLLVM_INCLUDE_EXAMPLES=Off -DLLVM_TARGETS_TO_BUILD="" -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="URCL" -DLLVM_ENABLE_OCAMLDOC=Off -DLLVM_BUILD_UTILS=Off -DLLVM_BUILD_DOCS=Off -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_OPTIMIZED_TABLEGEN=On -DCLANG_INCLUDE_TESTS=Off -DCLANG_BUILD_EXAMPLES=Off -DCMAKE_BUILD_TYPE="Debug" -DLLVM_ENABLE_ASSERTIONS=On ../llvm

cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fuse-ld=mold" -DLLVM_TARGETS_TO_BUILD="" -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="URCL" -DLLVM_ENABLE_OCAMLDOC=Off -DLLVM_BUILD_DOCS=Off -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_OPTIMIZED_TABLEGEN=On -DCMAKE_BUILD_TYPE="Debug" -DLLVM_ENABLE_ASSERTIONS=On ../llvm

#cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fuse-ld=mold" -DLLVM_TARGETS_TO_BUILD="" -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="URCL" -DLLVM_ENABLE_OCAMLDOC=Off -DLLVM_BUILD_DOCS=Off -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_ENABLE_RUNTIMES="libcxx" -DLLVM_RUNTIME_TARGETS="i386-unknown-linux-gnu"  -DLLVM_OPTIMIZED_TABLEGEN=On -DCMAKE_BUILD_TYPE="Debug" -DLLVM_ENABLE_ASSERTIONS=On ../llvm



#-DCMAKE_BUILD_TYPE=MinSizeRel \

